'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { api, API_URL } from '@/lib/api';

type Status = 'SUBMITTED'|'UNDER_REVIEW'|'VERIFIED'|'REJECTED'|'RESUBMISSION_REQUIRED';
type QueueRow={verification:{id:string;status:Status;submittedAt:string;reviewedAt?:string|null;userSafeReason?:string|null};profile:{displayName:string};intake:{serviceYear:string;batch:string;stream:string};camp:{stateName:string;campName:string}};
type Detail=QueueRow&{profile:{displayName:string;firstName?:string;lastNamePrivate?:string};documents:Array<{id:string;documentType:string;mimeType:string;uploadedAt:string;status:string}>};
type Notice={kind:'success'|'error';text:string}|null;
const statuses:Status[]=['SUBMITTED','UNDER_REVIEW','VERIFIED','RESUBMISSION_REQUIRED','REJECTED'];
const labels:Record<Status,string>={SUBMITTED:'Submitted',UNDER_REVIEW:'Under review',VERIFIED:'Verified',REJECTED:'Rejected',RESUBMISSION_REQUIRED:'Resubmission required'};
const reasons=['DOCUMENT_UNREADABLE','DOCUMENT_INCOMPLETE','POSTING_INFORMATION_MISMATCH','UNABLE_TO_VERIFY','DUPLICATE_OR_SUSPICIOUS_SUBMISSION','OTHER'];
const stamp=(value?:string|null)=>value?new Intl.DateTimeFormat('en-NG',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'—';
const age=(value:string)=>{const hours=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/36e5));return hours<24?`${hours}h`:`${Math.floor(hours/24)}d`};
function Badge({status}:{status:Status}){return <span className={`verify-badge ${status.toLowerCase().replaceAll('_','-')}`}>{labels[status]}</span>}
function Brand(){return <span className="verify-brand"><span aria-hidden="true"><i/><i/><i/><i/></span><b>Kopa-Padi<small>Admin</small></b></span>}

export function AdminQueue(){
  const [records,setRecords]=useState<Record<Status,QueueRow[]>>({SUBMITTED:[],UNDER_REVIEW:[],VERIFIED:[],REJECTED:[],RESUBMISSION_REQUIRED:[]});
  const [active,setActive]=useState<Status>('SUBMITTED'),[selected,setSelected]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false),[saving,setSaving]=useState(false);
  const [search,setSearch]=useState(''),[notice,setNotice]=useState<Notice>(null),[dialog,setDialog]=useState<'approve'|'reject'|'resubmit'|null>(null),[panelTab,setPanelTab]=useState<'overview'|'documents'|'review'|'history'>('overview'),[mobileNav,setMobileNav]=useState(false);
  const load=useCallback(async(show=true)=>{if(show)setLoading(true);try{const replies=await Promise.all(statuses.map((status)=>api<QueueRow[]>(`/admin/verifications?status=${status}`)));setRecords(Object.fromEntries(statuses.map((status,index)=>[status,replies[index]])) as Record<Status,QueueRow[]>)}catch(error){setNotice({kind:'error',text:error instanceof Error?error.message:"We couldn't load the verification queue."})}finally{if(show)setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const rows=useMemo(()=>records[active].filter((row)=>{const terms=`${row.profile.displayName} ${row.verification.id} ${row.camp.campName} ${row.camp.stateName} ${row.intake.serviceYear} ${row.intake.batch} ${row.intake.stream}`.toLowerCase();return terms.includes(search.toLowerCase())}),[records,active,search]);
  const all=useMemo(()=>statuses.flatMap((status)=>records[status]),[records]);
  const today=all.filter((row)=>new Date(row.verification.submittedAt).toDateString()===new Date().toDateString()).length;
  const open=async(id:string)=>{setDetailLoading(true);setNotice(null);try{const detail=await api<Detail>(`/admin/verifications/${id}`);setSelected(detail);setPanelTab('overview')}catch(error){setNotice({kind:'error',text:error instanceof Error?error.message:"We couldn't load this application."})}finally{setDetailLoading(false)}};
  const refreshSelected=async(id:string)=>{try{setSelected(await api<Detail>(`/admin/verifications/${id}`))}catch(error){setNotice({kind:'error',text:error instanceof Error?error.message:'Refresh application'})}};
  const transition=async(kind:'start-review'|'approve'|'reject'|'request-resubmission',event?:FormEvent<HTMLFormElement>)=>{event?.preventDefault();if(!selected)return;const form=event?new FormData(event.currentTarget):new FormData();const body:Record<string,unknown>={expectedStatus:selected.verification.status};if(form.get('reasonCode'))body.reasonCode=form.get('reasonCode');if(form.get('userSafeReason'))body.userSafeReason=form.get('userSafeReason');if(form.get('reviewNotesPrivate'))body.reviewNotesPrivate=form.get('reviewNotesPrivate');setSaving(true);try{await api(`/admin/verifications/${selected.verification.id}/${kind}`,{method:'POST',body:JSON.stringify(body)});setDialog(null);setNotice({kind:'success',text:kind==='start-review'?'Review started':kind==='approve'?'Verification approved':kind==='reject'?'Verification rejected':'Resubmission requested'});await Promise.all([load(false),refreshSelected(selected.verification.id)])}catch(error){const text=error instanceof Error?error.message:"We couldn't complete this review action. Please try again.";setNotice({kind:'error',text:text.includes('Self-review')?'You cannot review your own verification submission.':text.includes('changed')?'This verification was updated by another reviewer. Refresh application.':text})}finally{setSaving(false)}};
  const documentUrl=(documentId:string)=>selected?`${API_URL}/api/admin/verifications/${selected.verification.id}/documents/${documentId}`:'#';
  return <div className="verify-admin">
    <aside className="verify-sidebar"><Brand/><nav><a href="/admin/operations">⌂ <span>Dashboard</span></a><span>♙ <b>Users</b></span><a className="active" href="/admin/verifications">◇ <span>Verifications</span></a><span>♧ <b>Matches</b></span><span>▣ <b>Travel Plans</b></span><a href="/admin/geography">⌘ <span>Geography</span></a><a href="/admin/journey-guides">▤ <span>Journey Guides</span></a><a href="/admin/operations">▣ <span>Operations</span></a><span>▥ <b>Reports</b></span><a href="/admin/safety">⌾ <span>Safety</span></a><span>▤ <b>Content</b></span><span>☷ <b>Audit Logs</b></span><span>⚙ <b>Settings</b></span></nav></aside>
    {mobileNav?<div className="verify-mobile-nav" role="dialog" aria-label="Admin navigation"><div><button onClick={()=>setMobileNav(false)} aria-label="Close menu">×</button><Brand/><a href="/admin/operations">Dashboard</a><a href="/admin/verifications">Verifications</a><a href="/admin/geography">Geography</a><a href="/admin/safety">Safety</a></div></div>:null}
    <main className="verify-main"><header className="verify-mobile-head"><Brand/><button onClick={()=>setMobileNav(true)} aria-label="Open admin menu">☰</button></header><header className="verify-page-head"><div><h1>Verification queue</h1><p>Review and manage PCM verification submissions.</p></div><label className="verify-global-search"><span>⌕</span><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search applicants, camp, intake or submission ID…"/></label><div className="verify-admin-user">♧ <span>A</span> Admin⌄</div></header>
      {notice?<div className={`verify-notice ${notice.kind}`} role="status"><b>{notice.kind==='success'?'✓':'!'}</b><span>{notice.text}</span>{notice.kind==='error'?<button onClick={()=>void load()}>Try again</button>:<button onClick={()=>setNotice(null)} aria-label="Dismiss">×</button>}</div>:null}
      {loading?<Loading/>:<><section className="verify-stats"><Stat icon="▧" value={today} label="Submitted today"/><Stat icon="◴" value={records.UNDER_REVIEW.length} label="Under review"/><Stat icon="✓" value={records.VERIFIED.length} label="Verified"/><Stat icon="↻" value={records.RESUBMISSION_REQUIRED.length} label="Resubmission required"/><Stat icon="×" value={records.REJECTED.length} label="Rejected"/><Stat icon="▤" value={all.length} label="All submissions"/></section>
      <section className="verify-workspace"><div className="verify-queue"><nav className="verify-status-tabs" aria-label="Verification status">{statuses.map((status)=><button className={active===status?'active':''} key={status} onClick={()=>{setActive(status);setSearch('')}}>{labels[status]} <b>({records[status].length})</b></button>)}</nav><div className="verify-filter"><label><span>⌕</span><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search by name, camp, intake…"/></label><span>Newest first</span></div>{rows.length?<div className="verify-table-wrap"><table><thead><tr><th>Applicant</th><th>Submitted</th><th>Intake</th><th>Orientation camp</th><th>Status</th><th>Age</th><th/></tr></thead><tbody>{rows.map((row)=><tr className={selected?.verification.id===row.verification.id?'selected':''} key={row.verification.id} onClick={()=>void open(row.verification.id)}><td><b>{row.profile.displayName}</b><small>#{row.verification.id.slice(0,8).toUpperCase()}</small></td><td>{stamp(row.verification.submittedAt)}</td><td>{row.intake.serviceYear}<small>{row.intake.batch} · {row.intake.stream}</small></td><td><b>{row.camp.campName}</b><small>{row.camp.stateName}</small></td><td><Badge status={row.verification.status}/></td><td>{age(row.verification.submittedAt)}</td><td>›</td></tr>)}</tbody></table></div>:<Empty title={search?'No results match this search.':`No ${labels[active].toLowerCase()} verifications.`}/>}</div>
        <ReviewPanel detail={selected} loading={detailLoading} tab={panelTab} setTab={setPanelTab} close={()=>setSelected(null)} start={()=>void transition('start-review')} approve={()=>setDialog('approve')} resubmit={()=>setDialog('resubmit')} reject={()=>setDialog('reject')} downloadUrl={documentUrl} saving={saving}/>
      </section></>}
    </main>
    {dialog&&selected?<DecisionDialog type={dialog} saving={saving} close={()=>setDialog(null)} submit={(event)=>void transition(dialog==='approve'?'approve':dialog==='reject'?'reject':'request-resubmission',event)}/>:null}
  </div>
}

function Stat({icon,value,label}:{icon:string;value:number;label:string}){return <article><span>{icon}</span><div><b>{value}</b><small>{label}</small></div></article>}
function Empty({title}:{title:string}){return <div className="verify-empty"><span>⌁</span><b>{title}</b><p>Change the queue status or adjust the search to continue.</p></div>}
function Loading(){return <div className="verify-loading"><div>{[0,1,2,3,4,5].map((item)=><i key={item}/>)}</div><section>{[0,1,2,3,4].map((item)=><i key={item}/>)}</section></div>}

function ReviewPanel({detail,loading,tab,setTab,close,start,approve,resubmit,reject,downloadUrl,saving}:{detail:Detail|null;loading:boolean;tab:'overview'|'documents'|'review'|'history';setTab:(tab:'overview'|'documents'|'review'|'history')=>void;close:()=>void;start:()=>void;approve:()=>void;resubmit:()=>void;reject:()=>void;downloadUrl:(id:string)=>string;saving:boolean}){
  if(loading)return <aside className="verify-panel verify-detail-loading"><i/><i/><i/><i/></aside>;
  if(!detail)return <aside className="verify-panel verify-panel-empty"><span>◇</span><h2>Select an application</h2><p>Choose a verification from the queue to view identity, NYSC assignment and secure evidence.</p></aside>;
  const status=detail.verification.status;
  return <aside className="verify-panel"><header><div><h2>{detail.profile.displayName}</h2><small>#{detail.verification.id.slice(0,8).toUpperCase()}</small></div><Badge status={status}/><button onClick={close} aria-label="Close review panel">×</button></header><nav>{(['overview','documents','review','history'] as const).map((item)=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</nav>
    {tab==='overview'?<><section className="verify-card"><h3>Applicant information</h3><div className="verify-applicant"><span>♙</span><dl><div><dt>Display name</dt><dd>{detail.profile.displayName}</dd></div><div><dt>First name</dt><dd>{detail.profile.firstName??'Private'}</dd></div><div><dt>Last name <small>(private)</small></dt><dd>{detail.profile.lastNamePrivate??'Private'}</dd></div><div><dt>Submission ID</dt><dd>#{detail.verification.id.slice(0,8).toUpperCase()}</dd></div><div><dt>Submitted</dt><dd>{stamp(detail.verification.submittedAt)}</dd></div></dl></div></section><Assignment detail={detail}/><Timeline detail={detail}/></>:null}
    {tab==='documents'?<section className="verify-card"><h3>Verification documents ({detail.documents.length})</h3>{detail.documents.length?detail.documents.map((document)=><div className="verify-document" key={document.id}><span>▧</span><div><b>{document.documentType.replaceAll('_',' ')}</b><small>{document.mimeType} · Uploaded {stamp(document.uploadedAt)}</small></div><em>{document.status}</em><a href={downloadUrl(document.id)} target="_blank" rel="noreferrer">Download</a></div>):<Empty title="No documents available."/>}<p className="verify-secure-note">Downloads are restricted to admins, recorded in audit logs, and are never publicly cached.</p></section>:null}
    {tab==='review'?<section className="verify-card"><h3>Review decision</h3><p className="verify-card-copy">Review the applicant identity, NYSC assignment and secure evidence before deciding.</p>{status==='SUBMITTED'?<button className="verify-primary full" disabled={saving} onClick={start}>{saving?'Starting…':'Start review →'}</button>:status==='UNDER_REVIEW'?<div className="verify-decision-actions"><button className="verify-primary" onClick={approve}>Approve</button><button className="verify-amber" onClick={resubmit}>Request resubmission</button><button className="verify-danger" onClick={reject}>Reject</button></div>:<div className="verify-readonly"><b>This submission is view-only.</b><p>The current backend workflow does not allow another decision from this state.</p></div>}</section>:null}
    {tab==='history'?<section className="verify-card"><h3>Review timeline</h3><Timeline detail={detail}/><p className="verify-secure-note">Reviewer and audit-event history is not available through the current API. The recorded submission and decision timestamps are shown above.</p></section>:null}
    <footer>{status==='SUBMITTED'?<button className="verify-primary full" disabled={saving} onClick={start}>{saving?'Starting…':'Start review →'}</button>:status==='UNDER_REVIEW'?<><button className="verify-primary" onClick={approve}>Approve</button><button className="verify-amber" onClick={resubmit}>Resubmit</button><button className="verify-danger" onClick={reject}>Reject</button></>:null}</footer>
  </aside>
}
function Assignment({detail}:{detail:Detail}){return <section className="verify-card"><h3>NYSC assignment</h3><dl className="verify-assignment"><div><dt>Service year</dt><dd>{detail.intake.serviceYear}</dd></div><div><dt>Batch</dt><dd>{detail.intake.batch}</dd></div><div><dt>Stream</dt><dd>{detail.intake.stream}</dd></div><div><dt>Orientation camp</dt><dd>{detail.camp.campName}</dd></div><div><dt>State</dt><dd>{detail.camp.stateName}</dd></div></dl></section>}
function Timeline({detail}:{detail:Detail}){const status=detail.verification.status;return <section className="verify-card"><h3>Review timeline</h3><ol className="verify-timeline"><li className="done"><b>Submitted</b><small>{stamp(detail.verification.submittedAt)}</small></li><li className={status!=='SUBMITTED'?'done':''}><b>Under review</b><small>{status!=='SUBMITTED'?stamp(detail.verification.reviewedAt):'—'}</small></li><li className={['VERIFIED','REJECTED','RESUBMISSION_REQUIRED'].includes(status)?'done':''}><b>Decision</b><small>{['VERIFIED','REJECTED','RESUBMISSION_REQUIRED'].includes(status)?labels[status]:'—'}</small></li></ol></section>}
function DecisionDialog({type,saving,close,submit}:{type:'approve'|'reject'|'resubmit';saving:boolean;close:()=>void;submit:(event?:FormEvent<HTMLFormElement>)=>void}){const approve=type==='approve',reject=type==='reject';return <div className="verify-overlay"><section className={`verify-dialog ${reject?'danger':''}`} role="dialog" aria-modal="true" aria-labelledby="decision-title"><button className="verify-close" onClick={close} aria-label="Close">×</button><span>{approve?'✓':reject?'×':'↻'}</span><h2 id="decision-title">{approve?'Approve verification?':reject?'Reject this verification?':'Request a new submission?'}</h2><p>{approve?'This will mark the applicant as verified. They will be notified and can access travel planning and matching features.':reject?'The applicant will be notified and will not be verified from this submission.':'The applicant will be asked to upload corrected information or evidence and will be notified.'}</p>{approve?<div className="verify-dialog-actions"><button onClick={close}>Cancel</button><button className="verify-primary" disabled={saving} onClick={()=>submit()}>{saving?'Approving…':'Approve'}</button></div>:<form onSubmit={submit}><label>Reason code *<select name="reasonCode" required defaultValue=""><option value="" disabled>Select a reason</option>{reasons.map((reason)=><option key={reason} value={reason}>{reason.replaceAll('_',' ')}</option>)}</select></label><label>Message to applicant *<small>Visible to the applicant</small><textarea name="userSafeReason" required maxLength={500} placeholder="Explain what needs to be corrected…"/></label><label>Private reviewer note <small>Internal only — not visible to applicant</small><textarea name="reviewNotesPrivate" maxLength={500} placeholder="Internal context for the review team…"/></label><div className="verify-dialog-actions"><button type="button" onClick={close}>Cancel</button><button className={reject?'verify-danger':'verify-amber'} disabled={saving}>{saving?'Saving…':reject?'Reject verification':'Request resubmission'}</button></div></form>}</section></div>}
