'use client';

import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';

type Tab = 'camps'|'hubs'|'coverage'|'proximity'|'debug';
type StateRow = { id:string; name:string; code:string };
type Lga = { id:string; stateId:string; name:string };
type Camp = { id:string; stateId:string|null; lgaId:string|null; campName:string; officialAddress:string|null; latitude:string|null; longitude:string|null; status:'ACTIVE'|'TEMPORARY'|'INACTIVE'|'UNKNOWN'; sourceReference:string|null; lastVerifiedAt?:string|null; updatedAt?:string };
type CampRow = { camp:Camp; state?:StateRow|null; lga?:Lga|null };
type Hub = { id:string; name:string; stateId:string; lgaId:string|null; townId:string|null; latitude:string|null; longitude:string|null; hubType:'LOCAL'|'REGIONAL'|'INTERSTATE'|'DESTINATION_GATEWAY'; status:'ACTIVE'|'INACTIVE'|'REVIEW_REQUIRED'; updatedAt?:string };
type HubRow = { hub:Hub; state:StateRow; lga?:Lga|null };
type Source = 'MANUAL_REVIEW'|'OSRM'|'OPENSTREETMAP'|'IMPORTED_DATASET';
type Coverage = { travelHubId:string; lgaId:string; estimatedMinutes:number; isPrimary:boolean; source:Source; lastVerifiedAt?:string|null };
type HubDetail = HubRow & { coverage:Array<{coverage:Coverage;lga:Lga}> };
type Pair = { id:string; lgaAId:string; lgaBId:string; estimatedRoadMinutes:number; estimatedRoadDistanceKm:string|null; commonHubId:string|null; isNearby:boolean; source:Source; lastVerifiedAt?:string|null };
type Notice = {kind:'success'|'error';text:string}|null;

const tabs:Array<{id:Tab;label:string}> = [
  {id:'camps',label:'Orientation Camps'},{id:'hubs',label:'Travel Hubs'},
  {id:'coverage',label:'Hub Coverage'},{id:'proximity',label:'LGA Proximity'},
  {id:'debug',label:'Compatibility Debug'},
];
const sources:Source[] = ['MANUAL_REVIEW','OSRM','OPENSTREETMAP','IMPORTED_DATASET'];
const pretty = (value:string) => value.toLowerCase().split('_').map((word)=>word[0].toUpperCase()+word.slice(1)).join(' ');
const date = (value?:string|null) => value ? new Intl.DateTimeFormat('en-NG',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value)) : 'Not reviewed';

function Brand(){return <span className="geo-brand"><span className="geo-brand-mark" aria-hidden="true"><i/><i/><i/><i/></span><span><b>Kopa-Padi</b><small>Admin</small></span></span>}
function Badge({value,tone}:{value:string;tone?:string}){return <span className={`geo-badge ${tone??value.toLowerCase().replaceAll('_','-')}`}>{pretty(value)}</span>}
function Glyph({children}:{children:ReactNode}){return <span className="geo-glyph" aria-hidden="true">{children}</span>}
function Empty({title,body}:{title:string;body:string}){return <div className="geo-empty"><Glyph>⌁</Glyph><b>{title}</b><p>{body}</p></div>}

export function GeographyAdmin(){
  const [tab,setTab]=useState<Tab>('camps');
  const [states,setStates]=useState<StateRow[]>([]),[lgas,setLgas]=useState<Lga[]>([]);
  const [camps,setCamps]=useState<CampRow[]>([]),[hubs,setHubs]=useState<HubRow[]>([]),[pairs,setPairs]=useState<Pair[]>([]);
  const [coverage,setCoverage]=useState<HubDetail|null>(null),[hubId,setHubId]=useState('');
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[coverageLoading,setCoverageLoading]=useState(false);
  const [notice,setNotice]=useState<Notice>(null),[editor,setEditor]=useState<'camp'|'hub'|'coverage'|'pair'|null>(null);
  const [editCamp,setEditCamp]=useState<CampRow|null>(null),[editHub,setEditHub]=useState<HubRow|null>(null),[editPair,setEditPair]=useState<Pair|null>(null);
  const [confirm,setConfirm]=useState<{title:string;body:string;run:()=>Promise<void>}|null>(null);
  const [search,setSearch]=useState(''),[stateFilter,setStateFilter]=useState(''),[statusFilter,setStatusFilter]=useState('');
  const [page,setPage]=useState(1),[debugResult,setDebugResult]=useState<Record<string,unknown>|null>(null),[navOpen,setNavOpen]=useState(false);

  const load=useCallback(async(showSkeleton=true)=>{
    if(showSkeleton)setLoading(true);
    try{
      const [stateRows,campRows,hubRows,pairRows]=await Promise.all([
        api<StateRow[]>('/locations/states'),api<CampRow[]>('/orientation-camps'),
        api<HubRow[]>('/admin/geography/hubs'),api<Pair[]>('/admin/geography/proximities'),
      ]);
      const responses=await Promise.allSettled(stateRows.map((state)=>api<Lga[]>(`/locations/states/${state.id}/lgas`)));
      setStates(stateRows);setLgas(responses.flatMap((item)=>item.status==='fulfilled'?item.value:[]));
      setCamps(campRows);setHubs(hubRows);setPairs(pairRows);setHubId((current)=>current||hubRows[0]?.hub.id||'');
    }catch(error){setNotice({kind:'error',text:error instanceof Error?error.message:"We couldn't load geography data."})}
    finally{if(showSkeleton)setLoading(false)}
  },[]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{
    if(tab!=='coverage'||!hubId)return;
    setCoverageLoading(true);
    api<HubDetail>(`/travel-hubs/${hubId}`).then(setCoverage).catch((error)=>setNotice({kind:'error',text:error instanceof Error?error.message:'Coverage load failed'})).finally(()=>setCoverageLoading(false));
  },[tab,hubId]);
  useEffect(()=>{if(!editor&&!confirm)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){setEditor(null);setConfirm(null)}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[editor,confirm]);

  const lgaMap=useMemo(()=>new Map(lgas.map((row)=>[row.id,row])),[lgas]);
  const stateMap=useMemo(()=>new Map(states.map((row)=>[row.id,row])),[states]);
  const hubMap=useMemo(()=>new Map(hubs.map((row)=>[row.hub.id,row.hub])),[hubs]);
  const filteredCamps=useMemo(()=>camps.filter(({camp,state,lga})=>(!search||`${camp.campName} ${state?.name??''} ${lga?.name??''}`.toLowerCase().includes(search.toLowerCase()))&&(!stateFilter||camp.stateId===stateFilter)&&(!statusFilter||(statusFilter==='UNMAPPED'?!camp.stateId:camp.status===statusFilter))),[camps,search,stateFilter,statusFilter]);
  const filteredHubs=useMemo(()=>hubs.filter(({hub,state,lga})=>(!search||`${hub.name} ${state.name} ${lga?.name??''}`.toLowerCase().includes(search.toLowerCase()))&&(!stateFilter||hub.stateId===stateFilter)&&(!statusFilter||hub.status===statusFilter||hub.hubType===statusFilter)),[hubs,search,stateFilter,statusFilter]);
  const filteredPairs=useMemo(()=>pairs.filter((pair)=>!search||`${lgaMap.get(pair.lgaAId)?.name??pair.lgaAId} ${lgaMap.get(pair.lgaBId)?.name??pair.lgaBId}`.toLowerCase().includes(search.toLowerCase())),[pairs,search,lgaMap]);
  const stats=[
    {icon:'△',value:camps.length,label:'Orientation camps',note:`${camps.filter(({camp})=>camp.status==='ACTIVE').length} active`},
    {icon:'▥',value:hubs.length,label:'Travel hubs',note:`${hubs.filter(({hub})=>hub.status==='REVIEW_REQUIRED').length} awaiting review`},
    {icon:'⌘',value:pairs.length,label:'LGA proximity pairs',note:`${pairs.filter((pair)=>pair.isNearby).length} marked nearby`},
    {icon:'◇',value:camps.filter(({camp})=>!camp.stateId).length,label:'Unmapped camps',note:'Canonical mapping required'},
  ];
  const switchTab=(next:Tab)=>{setTab(next);setSearch('');setStateFilter('');setStatusFilter('');setPage(1)};
  const openCamp=(row:CampRow|null=null)=>{setEditCamp(row);setEditor('camp')};
  const openHub=(row:HubRow|null=null)=>{setEditHub(row);setEditor('hub')};
  const openPair=(row:Pair|null=null)=>{setEditPair(row);setEditor('pair')};
  async function mutate(path:string,method:'POST'|'PATCH',body:Record<string,unknown>,message:string){setSaving(true);try{await api(path,{method,body:JSON.stringify(body)});setEditor(null);setNotice({kind:'success',text:message});await load(false);if(tab==='coverage'&&hubId)setCoverage(await api<HubDetail>(`/travel-hubs/${hubId}`))}catch(error){setNotice({kind:'error',text:error instanceof Error?error.message:'Save failed'})}finally{setSaving(false)}}
  function status(kind:'camp'|'hub',row:CampRow|HubRow,next:string){const name=kind==='camp'?(row as CampRow).camp.campName:(row as HubRow).hub.name;setConfirm({title:`${pretty(next)} ${kind}?`,body:`This changes whether ${name} is available to operational geography workflows.`,run:async()=>{setConfirm(null);if(kind==='camp'){const x=(row as CampRow).camp;await mutate(`/admin/geography/camps/${x.id}`,'PATCH',{stateId:x.stateId,lgaId:x.lgaId,name:x.campName,officialAddress:x.officialAddress,latitude:x.latitude?Number(x.latitude):null,longitude:x.longitude?Number(x.longitude):null,status:next,sourceReference:x.sourceReference},`Camp ${next==='ACTIVE'?'activated':'deactivated'}`)}else{const x=(row as HubRow).hub;await mutate(`/admin/geography/hubs/${x.id}`,'PATCH',{name:x.name,stateId:x.stateId,lgaId:x.lgaId,townId:x.townId,latitude:x.latitude?Number(x.latitude):null,longitude:x.longitude?Number(x.longitude):null,hubType:x.hubType,status:next},next==='REVIEW_REQUIRED'?'Hub marked for review':`Hub ${next==='ACTIVE'?'activated':'deactivated'}`)}}})}

  const rows=tab==='camps'?filteredCamps:tab==='hubs'?filteredHubs:filteredPairs;
  const totalPages=Math.max(1,Math.ceil(rows.length/6));
  const current=Math.min(page,totalPages),slice=<T,>(items:T[])=>items.slice((current-1)*6,current*6);

  return <div className="geo-admin">
    <aside className="geo-sidebar"><a href="/admin/operations"><Brand/></a><nav aria-label="Admin navigation"><a href="/admin/operations">⌂ <span>Dashboard</span></a><span>♙ <b>Users</b></span><a href="/admin/verifications">◇ <span>Verifications</span></a><span>♧ <b>Matches</b></span><span>▣ <b>Travel Plans</b></span><a className="active" href="/admin/geography" aria-current="page">⌘ <span>Geography</span></a><span>▥ <b>Reports</b></span><a href="/admin/safety">⌾ <span>Safety</span></a><a href="/admin/journey-guides">▤ <span>Content</span></a><span>☷ <b>Audit Logs</b></span><span>⚙ <b>Settings</b></span></nav><a className="geo-back" href="/dashboard">← <span>Back to app</span></a></aside>
    {navOpen?<div className="geo-mobile-nav" role="dialog" aria-label="Admin navigation"><div><button aria-label="Close admin menu" onClick={()=>setNavOpen(false)}>×</button><Brand/><a href="/admin/operations">Dashboard</a><a href="/admin/verifications">Verifications</a><a href="/admin/geography">Geography</a><a href="/admin/safety">Safety</a><a href="/admin/journey-guides">Content</a></div></div>:null}
    <main className="geo-main">
      <header className="geo-mobile-head"><Brand/><button type="button" aria-label="Open admin menu" aria-expanded={navOpen} onClick={()=>setNavOpen(true)}>☰</button></header>
      <header className="geo-page-head"><div><h1>Geography administration</h1><p>States and LGAs are imported as canonical records, while camps, hubs, coverage, and reviewed proximity estimates are managed here.</p></div><button className="geo-user" type="button"><span>A</span>Admin⌄</button></header>
      <nav className="geo-tabs" aria-label="Geography sections">{tabs.map((item)=><button key={item.id} className={tab===item.id?'active':''} aria-current={tab===item.id?'page':undefined} onClick={()=>switchTab(item.id)}>{item.label}</button>)}</nav>
      <select className="geo-mobile-tabs geo-input" value={tab} aria-label="Geography section" onChange={(event)=>switchTab(event.target.value as Tab)}>{tabs.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select>
      {notice?<div className={`geo-notice ${notice.kind}`} role="status"><b>{notice.kind==='success'?'✓':'!'}</b><span>{notice.text}</span>{notice.kind==='error'?<button onClick={()=>void load()}>Try again</button>:<button aria-label="Dismiss" onClick={()=>setNotice(null)}>×</button>}</div>:null}
      {loading?<Loading/>:<>
        <section className="geo-stats" aria-label="Geography summary">{stats.map((item)=><article key={item.label}><Glyph>{item.icon}</Glyph><div><strong>{item.value}</strong><b>{item.label}</b><small>{item.note}</small></div></article>)}</section>
        <div className="geo-layout"><section className="geo-workspace">
          {tab==='camps'?<><WorkspaceHead title="Orientation camps" body="Manage NYSC orientation camps and their canonical locations." action="Add camp" onAction={()=>openCamp()}/><Filters placeholder="Search camps..." {...{search,setSearch,states,stateFilter,setStateFilter,statusFilter,setStatusFilter}} options={['ACTIVE','TEMPORARY','INACTIVE','UNKNOWN']}/>{filteredCamps.length?<><div className="geo-table-wrap"><table><thead><tr><th>Camp name</th><th>State</th><th>LGA</th><th>Status</th><th>Source reference</th><th>Last reviewed</th><th>Actions</th></tr></thead><tbody>{slice(filteredCamps).map((row)=><tr key={row.camp.id}><td><b>{row.camp.campName}</b>{!row.camp.stateId?<Badge value="Needs mapping" tone="needs-mapping"/>:null}</td><td>{row.state?.name??'—'}</td><td>{row.lga?.name??'—'}</td><td><Badge value={row.camp.status}/></td><td>{row.camp.sourceReference??'—'}</td><td>{date(row.camp.lastVerifiedAt)}</td><td><div className="geo-actions">{row.camp.stateId?<button onClick={()=>status('camp',row,row.camp.status==='ACTIVE'?'INACTIVE':'ACTIVE')}>{row.camp.status==='ACTIVE'?'Deactivate':'Activate'}</button>:null}<button disabled={!row.camp.stateId} onClick={()=>openCamp(row)}>Edit</button></div></td></tr>)}</tbody></table></div><Pager page={current} pages={totalPages} count={filteredCamps.length} setPage={setPage}/></>:<Empty title="No camps match these filters" body="Reset the filters or add a new orientation camp."/>}</>:null}
          {tab==='hubs'?<><WorkspaceHead title="Travel hubs" body="Manage operational convergence points used by compatible travel groups." action="Add hub" onAction={()=>openHub()}/><Filters placeholder="Search hubs..." {...{search,setSearch,states,stateFilter,setStateFilter,statusFilter,setStatusFilter}} options={['ACTIVE','REVIEW_REQUIRED','INACTIVE','LOCAL','REGIONAL','INTERSTATE','DESTINATION_GATEWAY']}/>{filteredHubs.length?<><div className="geo-table-wrap"><table><thead><tr><th>Hub name</th><th>State / LGA</th><th>Type</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{slice(filteredHubs).map((row)=><tr key={row.hub.id}><td><b>{row.hub.name}</b></td><td>{row.state.name}{row.lga?` / ${row.lga.name}`:''}</td><td><Badge value={row.hub.hubType} tone="type"/></td><td><Badge value={row.hub.status}/></td><td>{date(row.hub.updatedAt)}</td><td><div className="geo-actions"><button onClick={()=>status('hub',row,row.hub.status==='ACTIVE'?'INACTIVE':'ACTIVE')}>{row.hub.status==='ACTIVE'?'Deactivate':'Activate'}</button>{row.hub.status!=='REVIEW_REQUIRED'?<button onClick={()=>status('hub',row,'REVIEW_REQUIRED')}>Review</button>:null}<button onClick={()=>openHub(row)}>Edit</button></div></td></tr>)}</tbody></table></div><Pager page={current} pages={totalPages} count={filteredHubs.length} setPage={setPage}/></>:<Empty title="No hubs match these filters" body="Reset the filters or add a new travel hub."/>}</>:null}
          {tab==='coverage'?<><WorkspaceHead title="Hub coverage" body="Define which travel hub serves each LGA and how long it typically takes to reach it." action="Assign coverage" onAction={()=>setEditor('coverage')}/><label className="geo-hub-picker"><span>View coverage for</span><select className="geo-input" value={hubId} onChange={(event)=>setHubId(event.target.value)}>{hubs.map((row)=><option key={row.hub.id} value={row.hub.id}>{row.hub.name} — {row.state.name}</option>)}</select></label>{coverageLoading?<InlineLoading/>:coverage?.coverage.length?<div className="geo-table-wrap"><table><thead><tr><th>LGA</th><th>State</th><th>Assigned hub</th><th>Travel time</th><th>Priority</th><th>Source</th><th>Reviewed</th></tr></thead><tbody>{coverage.coverage.map((row)=><tr key={row.coverage.lgaId}><td><b>{row.lga.name}</b></td><td>{stateMap.get(row.lga.stateId)?.name??'—'}</td><td>{coverage.hub.name}</td><td>{row.coverage.estimatedMinutes} min</td><td><Badge value={row.coverage.isPrimary?'Primary':'Secondary'} tone={row.coverage.isPrimary?'active':'unknown'}/></td><td>{pretty(row.coverage.source)}</td><td>{date(row.coverage.lastVerifiedAt)}</td></tr>)}</tbody></table></div>:<Empty title="No coverage records found" body="Assign this hub to an LGA to establish coverage."/>}</>:null}
          {tab==='proximity'?<><WorkspaceHead title="LGA proximity" body="Manage reviewed relationships used to determine whether nearby LGAs can form compatible travel groups." action="Create pair" onAction={()=>openPair()}/><label className="geo-search-only"><span className="sr-only">Search pairs</span><input className="geo-input" placeholder="Search LGA pairs..." value={search} onChange={(event)=>setSearch(event.target.value)}/></label>{filteredPairs.length?<><div className="geo-table-wrap"><table><thead><tr><th>LGA A</th><th>LGA B</th><th>Road time</th><th>Distance</th><th>Nearby?</th><th>Common hub</th><th>Source</th><th>Reviewed</th><th/></tr></thead><tbody>{slice(filteredPairs).map((pair)=><tr key={pair.id}><td><b>{lgaMap.get(pair.lgaAId)?.name??pair.lgaAId}</b><small>{stateMap.get(lgaMap.get(pair.lgaAId)?.stateId??'')?.name}</small></td><td><b>{lgaMap.get(pair.lgaBId)?.name??pair.lgaBId}</b><small>{stateMap.get(lgaMap.get(pair.lgaBId)?.stateId??'')?.name}</small></td><td>{pair.estimatedRoadMinutes} min</td><td>{pair.estimatedRoadDistanceKm?`${pair.estimatedRoadDistanceKm} km`:'—'}</td><td><Badge value={pair.isNearby?'Nearby':'Not nearby'} tone={pair.isNearby?'active':'unknown'}/></td><td>{pair.commonHubId?hubMap.get(pair.commonHubId)?.name??'Unknown hub':'—'}</td><td>{pretty(pair.source)}</td><td>{date(pair.lastVerifiedAt)}</td><td><button className="geo-link" onClick={()=>openPair(pair)}>Edit</button></td></tr>)}</tbody></table></div><Pager page={current} pages={totalPages} count={filteredPairs.length} setPage={setPage}/></>:<Empty title="No proximity pairs found" body="Create a reviewed relationship between two LGAs."/>}</>:null}
          {tab==='debug'?<DebugPanel lgas={lgas} saving={saving} result={debugResult} hubs={hubMap} onSubmit={async(a,b)=>{setSaving(true);setDebugResult(null);try{setDebugResult(await api<Record<string,unknown>>(`/admin/geography/compatibility?lgaA=${encodeURIComponent(a)}&lgaB=${encodeURIComponent(b)}`))}catch(error){setNotice({kind:'error',text:error instanceof Error?error.message:'Lookup failed'})}finally{setSaving(false)}}}/>:null}
        </section><ContextPanel camps={camps} hubs={hubs} go={switchTab} setStatusFilter={setStatusFilter}/></div>
        <section className="geo-notes"><article><h3>Canonical data</h3><p>States and LGAs are maintained through the imported canonical dataset. They cannot be created from this workspace.</p></article><article><h3>Operational notes</h3><ul><li>Use canonical records for every location.</li><li>Keep new hubs in review until verified.</li><li>Record a source for travel-time data.</li><li>Verify changes with compatibility diagnostics.</li></ul></article></section>
      </>}
    </main>
    {editor?<Editor kind={editor} close={()=>setEditor(null)} {...{states,lgas,hubs,saving,editCamp,editHub,editPair,hubId,sources,mutate}}/>:null}
    {confirm?<div className="geo-overlay"><section className="geo-confirm" role="alertdialog" aria-modal="true" aria-labelledby="geo-confirm-title"><Glyph>!</Glyph><h2 id="geo-confirm-title">{confirm.title}</h2><p>{confirm.body}</p><div><button onClick={()=>setConfirm(null)}>Cancel</button><button className="geo-primary" onClick={()=>void confirm.run()}>Confirm change</button></div></section></div>:null}
  </div>
}

function Loading(){return <div className="geo-loading" aria-label="Loading geography data"><div>{[0,1,2,3].map((x)=><i key={x}/>)}</div><section>{[0,1,2,3,4].map((x)=><i key={x}/>)}</section></div>}
function InlineLoading(){return <div className="geo-inline-loading" aria-label="Loading coverage"><i/><i/><i/></div>}
function WorkspaceHead({title,body,action,onAction}:{title:string;body:string;action?:string;onAction?:()=>void}){return <header className="geo-workspace-head"><div><h2>{title}</h2><p>{body}</p></div>{action?<button className="geo-primary" onClick={onAction}>＋ {action}</button>:null}</header>}
function Pager({page,pages,count,setPage}:{page:number;pages:number;count:number;setPage:(page:number)=>void}){return <footer className="geo-pager"><span>Showing {Math.min((page-1)*6+1,count)}–{Math.min(page*6,count)} of {count}</span><div><button disabled={page<=1} onClick={()=>setPage(page-1)}>‹</button><b>{page}</b><span>of {pages}</span><button disabled={page>=pages} onClick={()=>setPage(page+1)}>›</button></div></footer>}

type FiltersProps={placeholder:string;search:string;setSearch:(x:string)=>void;states:StateRow[];stateFilter:string;setStateFilter:(x:string)=>void;statusFilter:string;setStatusFilter:(x:string)=>void;options:string[]};
function Filters({placeholder,search,setSearch,states,stateFilter,setStateFilter,statusFilter,setStatusFilter,options}:FiltersProps){return <div className="geo-filters"><label><span className="sr-only">Search</span><input className="geo-input" placeholder={placeholder} value={search} onChange={(e)=>setSearch(e.target.value)}/></label><select className="geo-input" aria-label="Filter by state" value={stateFilter} onChange={(e)=>setStateFilter(e.target.value)}><option value="">All states</option>{states.map((state)=><option key={state.id} value={state.id}>{state.name}</option>)}</select><select className="geo-input" aria-label="Filter by status or type" value={statusFilter} onChange={(e)=>setStatusFilter(e.target.value)}><option value="">All statuses</option>{options.map((value)=><option key={value} value={value}>{pretty(value)}</option>)}</select>{search||stateFilter||statusFilter?<button onClick={()=>{setSearch('');setStateFilter('');setStatusFilter('')}}>Reset</button>:null}</div>}

function ContextPanel({camps,hubs,go,setStatusFilter}:{camps:CampRow[];hubs:HubRow[];go:(tab:Tab)=>void;setStatusFilter:(x:string)=>void}){
  const points=[...camps.filter(({camp})=>camp.status==='ACTIVE'&&camp.latitude&&camp.longitude).map(({camp})=>({name:camp.campName,lat:Number(camp.latitude),lon:Number(camp.longitude),type:'camp'})),...hubs.filter(({hub})=>hub.status==='ACTIVE'&&hub.latitude&&hub.longitude).map(({hub})=>({name:hub.name,lat:Number(hub.latitude),lon:Number(hub.longitude),type:'hub'}))].slice(0,16);
  const place=(lat:number,lon:number)=>({left:`${Math.max(5,Math.min(95,((lon-2.5)/12.5)*100))}%`,top:`${Math.max(5,Math.min(95,((14.2-lat)/10)*100))}%`});
  return <aside className="geo-context"><section className="geo-map"><h3>Map preview</h3><div><span className="geo-nigeria"/>{points.map((point)=><button key={`${point.type}-${point.name}`} className={point.type} style={place(point.lat,point.lon)} title={point.name} aria-label={point.name}><i/></button>)}</div><footer><span><i className="camp"/>Orientation camp</span><span><i className="hub"/>Travel hub</span></footer></section><section className="geo-info"><Glyph>i</Glyph><p>Map shows active camps and hubs with saved coordinates. Select a record to review its location.</p></section><section className="geo-quick"><h3>Quick actions</h3><button onClick={()=>go('camps')}>View unmapped camps <span>›</span></button><button onClick={()=>{go('hubs');setStatusFilter('REVIEW_REQUIRED')}}>View hubs requiring review <span>›</span></button><button onClick={()=>go('debug')}>Open compatibility lookup <span>›</span></button></section></aside>
}

function Field({label,required,children}:{label:string;required?:boolean;children:ReactNode}){return <label className="geo-field"><span>{label}{required?<em> *</em>:null}</span>{children}</label>}
function StateSelect({states,value,set}:{states:StateRow[];value:string;set:(x:string)=>void}){return <select className="geo-input" name="stateId" required value={value} onChange={(e)=>set(e.target.value)}><option value="">Select state</option>{states.map((state)=><option key={state.id} value={state.id}>{state.name}</option>)}</select>}
function LgaSelect({lgas,stateId,value,set,name='lgaId',required=false}:{lgas:Lga[];stateId?:string;value:string;set:(x:string)=>void;name?:string;required?:boolean}){const rows=stateId?lgas.filter((lga)=>lga.stateId===stateId):lgas;return <select className="geo-input" name={name} required={required} value={value} onChange={(e)=>set(e.target.value)}><option value="">Select LGA{required?'':' (optional)'}</option>{rows.map((lga)=><option key={lga.id} value={lga.id}>{lga.name}</option>)}</select>}
function Actions({saving,label,close,disabled=false}:{saving:boolean;label:string;close:()=>void;disabled?:boolean}){return <div className="geo-editor-actions"><button type="button" onClick={close}>Cancel</button><button className="geo-primary" disabled={saving||disabled}>{saving?'Saving…':label}</button></div>}

type EditorProps={kind:'camp'|'hub'|'coverage'|'pair';close:()=>void;states:StateRow[];lgas:Lga[];hubs:HubRow[];saving:boolean;editCamp:CampRow|null;editHub:HubRow|null;editPair:Pair|null;hubId:string;sources:Source[];mutate:(path:string,method:'POST'|'PATCH',body:Record<string,unknown>,message:string)=>Promise<void>};
function Editor({kind,close,states,lgas,hubs,saving,editCamp,editHub,editPair,hubId,sources,mutate}:EditorProps){
  const [stateId,setStateId]=useState(kind==='camp'?editCamp?.camp.stateId??'':kind==='hub'?editHub?.hub.stateId??'':'');
  const [lgaId,setLgaId]=useState(kind==='camp'?editCamp?.camp.lgaId??'':kind==='hub'?editHub?.hub.lgaId??'':kind==='pair'?editPair?.lgaAId??'':'');
  const [otherLga,setOtherLga]=useState(editPair?.lgaBId??'');
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);
    if(kind==='camp'){const x=editCamp?.camp;await mutate(x?`/admin/geography/camps/${x.id}`:'/admin/geography/camps',x?'PATCH':'POST',{stateId,lgaId:lgaId||null,name:String(form.get('name')),officialAddress:String(form.get('officialAddress')||'')||null,latitude:form.get('latitude')?Number(form.get('latitude')):null,longitude:form.get('longitude')?Number(form.get('longitude')):null,status:String(form.get('status')),sourceReference:String(form.get('sourceReference')||'')||null},x?'Camp updated':'Camp added')}
    if(kind==='hub'){const x=editHub?.hub;await mutate(x?`/admin/geography/hubs/${x.id}`:'/admin/geography/hubs',x?'PATCH':'POST',{name:String(form.get('name')),stateId,lgaId:lgaId||null,townId:x?.townId??null,latitude:form.get('latitude')?Number(form.get('latitude')):null,longitude:form.get('longitude')?Number(form.get('longitude')):null,hubType:String(form.get('hubType')),status:String(form.get('status'))},x?'Hub updated':'Hub added')}
    if(kind==='coverage')await mutate(`/admin/geography/hubs/${String(form.get('hubId'))}/coverage`,'POST',{lgaId,estimatedMinutes:Number(form.get('estimatedMinutes')),isPrimary:form.get('isPrimary')==='on',source:String(form.get('source'))},'Coverage updated');
    if(kind==='pair'){const x=editPair;await mutate(x?`/admin/geography/proximities/${x.id}`:'/admin/geography/proximities',x?'PATCH':'POST',{lgaAId:lgaId,lgaBId:otherLga,estimatedRoadMinutes:Number(form.get('estimatedRoadMinutes')),estimatedRoadDistanceKm:form.get('estimatedRoadDistanceKm')?Number(form.get('estimatedRoadDistanceKm')):null,commonHubId:String(form.get('commonHubId')||'')||null,source:String(form.get('source'))},'Proximity pair saved')}
  }
  const title=kind==='camp'?`${editCamp?'Edit':'Add new'} camp`:kind==='hub'?`${editHub?'Edit':'Add new'} hub`:kind==='coverage'?'Assign hub coverage':`${editPair?'Update':'Create'} proximity pair`;
  return <div className="geo-overlay" onMouseDown={(e)=>{if(e.target===e.currentTarget)close()}}><section className="geo-editor" role="dialog" aria-modal="true" aria-labelledby="geo-editor-title"><header><button aria-label="Close form" onClick={close}>←</button><div><h2 id="geo-editor-title">{title}</h2><p>Fields marked with * are required.</p></div><button aria-label="Close form" onClick={close}>×</button></header><form onSubmit={submit}>
    {kind==='camp'?<><Field label="Camp name" required><input className="geo-input" name="name" minLength={2} required defaultValue={editCamp?.camp.campName} placeholder="e.g. Iseyin Camp"/></Field><Field label="State" required><StateSelect states={states} value={stateId} set={(x)=>{setStateId(x);setLgaId('')}}/></Field><Field label="LGA (optional)"><LgaSelect lgas={lgas} stateId={stateId} value={lgaId} set={setLgaId}/></Field><Field label="Official address"><textarea className="geo-input" name="officialAddress" defaultValue={editCamp?.camp.officialAddress??''} placeholder="Enter official address"/></Field><div className="geo-form-grid"><Field label="Latitude"><input className="geo-input" name="latitude" type="number" step="any" min="-90" max="90" defaultValue={editCamp?.camp.latitude??''}/></Field><Field label="Longitude"><input className="geo-input" name="longitude" type="number" step="any" min="-180" max="180" defaultValue={editCamp?.camp.longitude??''}/></Field></div><Field label="Status" required><select className="geo-input" name="status" defaultValue={editCamp?.camp.status??'ACTIVE'}>{['ACTIVE','TEMPORARY','INACTIVE','UNKNOWN'].map((x)=><option key={x} value={x}>{pretty(x)}</option>)}</select></Field><Field label="Source reference"><input className="geo-input" name="sourceReference" defaultValue={editCamp?.camp.sourceReference??''} placeholder="e.g. NYSC official list"/></Field><Actions saving={saving} label={editCamp?'Save changes':'Add camp'} close={close}/></>:null}
    {kind==='hub'?<><Field label="Hub name" required><input className="geo-input" name="name" minLength={2} required defaultValue={editHub?.hub.name} placeholder="e.g. Ibadan Central"/></Field><Field label="State" required><StateSelect states={states} value={stateId} set={(x)=>{setStateId(x);setLgaId('')}}/></Field><Field label="LGA (optional)"><LgaSelect lgas={lgas} stateId={stateId} value={lgaId} set={setLgaId}/></Field><div className="geo-form-grid"><Field label="Latitude"><input className="geo-input" name="latitude" type="number" step="any" min="-90" max="90" defaultValue={editHub?.hub.latitude??''}/></Field><Field label="Longitude"><input className="geo-input" name="longitude" type="number" step="any" min="-180" max="180" defaultValue={editHub?.hub.longitude??''}/></Field></div><Field label="Hub type" required><select className="geo-input" name="hubType" defaultValue={editHub?.hub.hubType??'LOCAL'}>{['LOCAL','REGIONAL','INTERSTATE','DESTINATION_GATEWAY'].map((x)=><option key={x} value={x}>{pretty(x)}</option>)}</select></Field><Field label="Initial status" required><select className="geo-input" name="status" defaultValue={editHub?.hub.status??'REVIEW_REQUIRED'}>{['REVIEW_REQUIRED','ACTIVE','INACTIVE'].map((x)=><option key={x} value={x}>{pretty(x)}</option>)}</select></Field><Actions saving={saving} label={editHub?'Save changes':'Add hub'} close={close}/></>:null}
    {kind==='coverage'?<><Field label="Hub" required><select className="geo-input" name="hubId" defaultValue={hubId}>{hubs.map((row)=><option key={row.hub.id} value={row.hub.id}>{row.hub.name} — {row.state.name}</option>)}</select></Field><Field label="State" required><StateSelect states={states} value={stateId} set={(x)=>{setStateId(x);setLgaId('')}}/></Field><Field label="LGA" required><LgaSelect lgas={lgas} stateId={stateId} value={lgaId} set={setLgaId} required/></Field><Field label="Estimated travel time (minutes)" required><input className="geo-input" name="estimatedMinutes" type="number" min="0" max="1440" required placeholder="e.g. 45"/></Field><label className="geo-toggle"><span><b>Primary hub for this LGA?</b><small>Only one hub can be primary per LGA.</small></span><input name="isPrimary" type="checkbox"/><i/></label><Field label="Source" required><select className="geo-input" name="source">{sources.map((x)=><option key={x} value={x}>{pretty(x)}</option>)}</select></Field><Actions saving={saving} label="Save coverage" close={close}/></>:null}
    {kind==='pair'?<><Field label="LGA A" required><LgaSelect lgas={lgas} value={lgaId} set={setLgaId} required/></Field><Field label="LGA B" required><LgaSelect lgas={lgas} value={otherLga} set={setOtherLga} required/></Field><Field label="Estimated road time (minutes)" required><input className="geo-input" name="estimatedRoadMinutes" type="number" min="0" max="1440" required defaultValue={editPair?.estimatedRoadMinutes}/></Field><Field label="Road distance (km)"><input className="geo-input" name="estimatedRoadDistanceKm" type="number" step="0.01" min="0" max="10000" defaultValue={editPair?.estimatedRoadDistanceKm??''}/></Field><Field label="Common hub"><select className="geo-input" name="commonHubId" defaultValue={editPair?.commonHubId??''}><option value="">No common hub</option>{hubs.map((row)=><option key={row.hub.id} value={row.hub.id}>{row.hub.name}</option>)}</select></Field><Field label="Source" required><select className="geo-input" name="source" defaultValue={editPair?.source??'MANUAL_REVIEW'}>{sources.map((x)=><option key={x} value={x}>{pretty(x)}</option>)}</select></Field>{lgaId&&lgaId===otherLga?<p className="geo-field-error">Choose two different LGAs.</p>:null}<Actions saving={saving} disabled={lgaId===otherLga} label="Save pair" close={close}/></>:null}
  </form></section></div>
}

function DebugPanel({lgas,saving,result,hubs,onSubmit}:{lgas:Lga[];saving:boolean;result:Record<string,unknown>|null;hubs:Map<string,Hub>;onSubmit:(a:string,b:string)=>Promise<void>}){
  const [a,setA]=useState(''),[b,setB]=useState('');
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();void onSubmit(a,b)};
  const compatible=Boolean(result?.compatible),minutes=result?.estimatedMinutes??result?.estimated_minutes,hubId=String(result?.commonHubId??result?.common_hub_id??'');
  return <div className="geo-debug"><WorkspaceHead title="Compatibility lookup" body="Evaluate why two LGAs are or are not considered compatible."/><form onSubmit={submit}><div className="geo-form-grid"><Field label="LGA A" required><LgaSelect lgas={lgas} value={a} set={setA} required/></Field><Field label="LGA B" required><LgaSelect lgas={lgas} value={b} set={setB} required/></Field></div><button className="geo-primary" disabled={saving||!a||!b||a===b}>{saving?'Evaluating…':'Evaluate compatibility'}</button></form>{result?<section className={`geo-result ${compatible?'yes':'no'}`}><header><Glyph>{compatible?'✓':'×'}</Glyph><div><small>Compatibility decision</small><h3>{compatible?'Compatible':'Not compatible'}</h3></div></header><dl><div><dt>Estimated travel time</dt><dd>{minutes==null?'Not available':`${String(minutes)} min`}</dd></div><div><dt>Common hub</dt><dd>{hubId?hubs.get(hubId)?.name??hubId:'None'}</dd></div><div><dt>Reason</dt><dd>{String(result.reason??'Decision based on the available geography evidence.')}</dd></div></dl><details><summary>View raw response</summary><pre>{JSON.stringify(result,null,2)}</pre></details></section>:<div className="geo-debug-hint"><Glyph>?</Glyph><p>Select two different LGAs to inspect the decision and supporting evidence.</p></div>}</div>
}
