'use client';
import {FormEvent,useEffect,useState} from 'react';
import {api} from '@/lib/api';
type Guide={matchScope:string;confidence:string;guide:{id:string;title:string;summary:string;version:number;lastReviewedAt:string|null;alternativeNotes:string|null};destination:{name:string;address:string|null;informationType:string};guidanceType:string;legs:{id:string;sequenceNumber:number;legType:string;fromLabel:string;toLabel:string;transportMode:string|null;instruction:string;connectionNotes:string|null;safetyNotes:string|null;estimatedDurationMinutes:number|null;confidenceLevel:string;sourceType:string}[];sources:{id:string;sourceType:string;title:string;reference:string}[]};
const human=(v:string)=>v.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
export function JourneyGuidePanel({journeyStatus}:{journeyStatus:string}){
 const[g,setG]=useState<Guide|null>(null),[none,setNone]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false);
 useEffect(()=>{let live=true;api<Guide|{status:string}>('/journey-guides/recommended').then(r=>{if(!live)return;if('status'in r&&r.status==='NO_GUIDE_AVAILABLE')setNone(true);else setG(r as Guide)}).catch(e=>live&&setError(e.message));return()=>{live=false}},[]);
 if(error)return <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-black">Recommended Journey Guide</h2><p role="alert" className="mt-3 rounded-xl bg-danger/5 p-3 text-sm text-danger">{error}</p></section>;
 if(none)return <section className="rounded-2xl border bg-white p-6 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-xl bg-primary-light text-primary">MAP</span><h2 className="mt-4 text-lg font-black">No reviewed journey guide is available for this route yet.</h2><p className="mt-2 text-sm leading-6 text-muted">Your verified destination and Journey safety tools remain available. Kopa-Padi will not invent directions.</p></section>;
 if(!g)return <section className="animate-pulse rounded-2xl border bg-white p-5"><div className="h-5 w-56 rounded bg-slate-200"/><div className="mt-5 h-32 rounded-xl bg-slate-100"/></section>;
 async function feedback(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await api('/journey-guides/'+g!.guide.id+'/feedback',{method:'POST',body:JSON.stringify({wasUseful:d.get('useful')==='YES',wasAccurate:d.get('accurate'),finalConnectionAccurate:d.get('final')||null,issueType:d.get('issue')||null,comment:d.get('comment')||null})});setSent(true)}
 return <section className="rounded-2xl border bg-white p-5 shadow-sm sm:p-6">
  <div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Recommended Journey Guide</p><h2 className="mt-2 text-xl font-black">{g.guide.title}</h2></div><span className="rounded-full bg-success/10 px-3 py-1 text-xs font-bold text-success">Confidence: {human(g.confidence)}</span></div>
  <p className="mt-3 text-sm leading-6 text-muted">{g.guide.summary}</p>
  <div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-background px-3 py-1.5">Match: {human(g.matchScope)}</span><span className="rounded-full bg-background px-3 py-1.5">Version {g.guide.version}</span><span className="rounded-full bg-background px-3 py-1.5">{g.guide.lastReviewedAt?'Reviewed '+new Date(g.guide.lastReviewedAt).toLocaleDateString():'Review date unavailable'}</span></div>
  <p className="mt-5 rounded-xl border border-warning/20 bg-warning/5 p-3 text-xs leading-5 text-muted"><strong className="text-foreground">Reviewed guidance only.</strong> This is not live navigation and does not guarantee route safety.</p>
  <ol className="mt-6 space-y-4">{g.legs.map((l,i)=><li key={l.id} className="relative pl-10"><span className="absolute left-0 top-0 grid h-7 w-7 place-items-center rounded-full bg-primary text-xs font-black text-white">{i+1}</span>{i<g.legs.length-1?<span className="absolute left-[13px] top-7 h-[calc(100%+1rem)] border-l border-dashed border-primary/40"/>:null}<p className="text-xs font-bold uppercase tracking-wider text-primary">{human(l.legType)}{l.transportMode?' - '+human(l.transportMode):''}</p><h3 className="mt-1 font-bold">{l.fromLabel} <span className="text-primary">-&gt;</span> {l.toLabel}</h3><p className="mt-2 text-sm leading-6 text-muted">{l.instruction}</p>{l.connectionNotes?<p className="mt-2 text-sm"><strong>Connection:</strong> {l.connectionNotes}</p>:null}{l.safetyNotes?<p className="mt-2 rounded-lg bg-primary-light/35 p-3 text-xs"><strong>Safety note:</strong> {l.safetyNotes}</p>:null}{l.estimatedDurationMinutes?<small className="mt-2 block text-muted">Approx. {l.estimatedDurationMinutes} minutes; static estimate only.</small>:null}</li>)}</ol>
  {g.guide.alternativeNotes?<details className="mt-6 rounded-xl border p-4"><summary className="cursor-pointer font-bold">Alternative options</summary><p className="mt-3 text-sm text-muted">{g.guide.alternativeNotes}</p></details>:null}
  <details className="mt-3 rounded-xl border p-4"><summary className="cursor-pointer font-bold">Sources and provenance</summary><ul className="mt-3 space-y-2 text-sm text-muted">{g.sources.map(x=><li key={x.id}>{human(x.sourceType)} - {x.title}: {x.reference}</li>)}</ul></details>
  {journeyStatus==='COMPLETED'&&!sent?<form onSubmit={feedback} className="mt-6 grid gap-4 rounded-xl bg-background p-4"><h3 className="font-black">How accurate was this guide?</h3><label className="grid gap-2 text-sm font-bold">Was it useful?<select className="field" name="useful"><option value="YES">Yes</option><option value="NO">No</option></select></label><label className="grid gap-2 text-sm font-bold">Did it match your journey?<select className="field" name="accurate"><option>YES</option><option>MOSTLY</option><option>NO</option></select></label><label className="grid gap-2 text-sm font-bold">Final connection accuracy<select className="field" name="final"><option value="">Not answered</option><option>YES</option><option>NO</option><option>NOT_SURE</option></select></label><label className="grid gap-2 text-sm font-bold">Issue<select className="field" name="issue"><option value="">None</option>{['ROUTE_CHANGED','HUB_INCORRECT','FINAL_CONNECTION_INCORRECT','DURATION_INACCURATE','INSTRUCTION_UNCLEAR','SAFETY_CONCERN','OTHER'].map(x=><option key={x} value={x}>{human(x)}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">What should improve?<textarea className="field min-h-24 py-3" name="comment" maxLength={1000}/></label><button className="btn-primary">Submit private feedback</button></form>:null}
  {sent?<p role="status" className="mt-5 rounded-xl bg-success/10 p-3 text-sm font-bold text-success">Feedback submitted for admin review.</p>:null}
 </section>
}